In [1]:
import numpy as np

In [4]:
print("NumPy is a Python library used for fast numerical and array operations.")

NumPy is a Python library used for fast numerical and array operations.


In [3]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)

[10 20 30 40 50]


In [5]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)

[[1 2 3]
 [4 5 6]]


In [6]:
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Data Type:", matrix.dtype)

Shape: (2, 3)
Dimensions: 2
Data Type: int64


In [7]:
print(numbers[0])
print(numbers[2])
print(numbers[-1])

10
30
50


In [8]:
print(numbers[1:4])
print(numbers[:3])
print(numbers[2:])

[20 30 40]
[10 20 30]
[30 40 50]


In [9]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [ 3  7 11]
Subtraction: [1 1 1]
Multiplication: [ 2 12 30]
Division: [2.         1.33333333 1.2       ]


In [10]:
print(a + 10)
print(a * 2)

[12 14 16]
[ 4  8 12]


In [11]:
marks = np.array([80, 75, 90, 95, 70])

print("Sum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Sum: 410
Mean: 82.0
Maximum: 95
Minimum: 70
Standard Deviation: 9.273618495495704


In [12]:
student_marks = np.array([65, 78, 92, 88, 74])

print("Marks:", student_marks)
print("Average:", np.mean(student_marks))
print("Highest:", np.max(student_marks))
print("Lowest:", np.min(student_marks))

Marks: [65 78 92 88 74]
Average: 79.4
Highest: 92
Lowest: 65


In [5]:
marks = np.array([80, 75, 90, 95, 70])

print("Marks greater than 80:")
print(marks[marks > 80])

Marks greater than 80:
[90 95]


In [6]:
numbers = np.arange(1, 13)

matrix = numbers.reshape(3, 4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
matrix = np.array([
    [10,20,30],
    [40,50,60]
])

print("Row Sum:", np.sum(matrix, axis=1))
print("Column Sum:", np.sum(matrix, axis=0))

Row Sum: [ 60 150]
Column Sum: [50 70 90]


In [15]:
import numpy as np
from IPython.display import display, Markdown
print('Libraries imported successfully!')

Libraries imported successfully!


In [ ]:
name=input('Enter your name: ')
age=int(input('Enter your age: '))
print(f'Welcome {name}!')

days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
steps=[]; calories=[]; water=[]; sleep=[]
print('\nEnter your weekly fitness data')
for d in days:
    print(f'--- {d} ---')
    steps.append(int(input('Steps: ')))
    calories.append(int(input('Calories Burned: ')))
    water.append(float(input('Water Intake (L): ')))
    sleep.append(float(input('Sleep Hours: ')))

steps=np.array(steps)
calories=np.array(calories)
water=np.array(water)
sleep=np.array(sleep)
print('\nData stored successfully!')



In [3]:
import numpy as np

# Conclusion

In this notebook, I learned:

- Creating NumPy arrays
- 1D and 2D arrays
- Array indexing and slicing
- Mathematical operations
- Statistical functions
- Array-based calculations

NumPy makes numerical computations faster and more efficient than standard Python lists.